### ISSUE TITLE
Можно добавить в дистрибутив файлик и примером использования?

### ISSUE THREAD

**Issue by jan6xx** [shoman4eg/moy-nalog#16]
Огромное спасибо за единственную поддерживаемую библиотеку на PHP для самозанятых с таким богатым функционалом.

Извиняюсь за тупой вопрос, я начинающий разработчик, у меня не получилось через нее сгенерировать чек. После установки из composer и autoload вижу ошибку Undefined class 'ApiClient'. 

Можно добавить в дистрибутив файлик и примером использования?

Успехов!

**Comment by shoman4eg** [comment]
Это все что было написано?
Попробуй поставить какую-нибудь библиотеку http-client
`composer require guzzlehttp/guzzle:^7.0` или `composer require symfony/http-client`

Ок, позже добавлю в readme установку.
Просто есть неявная зависимость от http-client т.к библиотеки используют разные, кто-то guzzle кто-то от symfony. Поэтому не стал устанавливать как явную зависимость.

**Comment by shoman4eg** [comment]
Если не поможет, то скинь свой `composer.json`, проверю у себя.

**Comment by jan6xx** [comment]
Большое спасибо что ответили на мой вопрос.
Попробовал установить оба клиента и на них установить библиотеку - не помогло.

скрин IDE с ошибкой https://bit.ly/3Nm9sdb
composer.json https://bit.ly/3sHbpsW

**Comment by shoman4eg** [comment]
Класс ApiClient лежит в неймспейсе `\Shoman4eg\Nalog\` т.е надо использовать 
```php
$client = Shoman4eg\Nalog\ApiClient::create()
```

**Comment by jan6xx** [comment]
Огромное спасибо что уделили время помогли разобраться, заработало! Теперь чеки будут на автомате))
Если в readme появятся реквизиты для донатов буду рад отправить небольшую благодарность в поддержку проекта.

Успехов!

**Comment by shoman4eg** [comment]
Добавил ссылку на спонсирование проекта)
