### ISSUE TITLE
Время жизни accessToken

### ISSUE THREAD

**Issue by prologonline** [shoman4eg/moy-nalog#18]
Не подскажите, сколько "живет" accessToken? На время сессии или он бессрочный?
Привязывается-ли он на стороне npd.nalog.ru к определенной сущности(домену с которого пришел запрос или опят-же к  сессии). Или после получения им можно воспользоваться везде где угодно? Что-то не смог нигде найти этой информации.

**Comment by shoman4eg** [comment]
Можно получить токен и сделать json_decode там будет время когда он истекает, и должен быть функционал, который рефрешит истекший токен, но его. Мне так и не удалось проверить, т.к у меня нет личного кабинета)
 По сути, весь клиент это все что удалось вытянуть с личного кабинета и с мобильного приложения. Так что не уверен что он привязывается к какому-либо домену. Получается что можно пользоваться где угодно.

**Comment by shoman4eg** [comment]
Если посмотреть на сам метод авторизации, видно что передается реферер сам сайт кабинета. https://github.com/shoman4eg/moy-nalog/blob/9c6c89f4b9b789535d7c1b4435ea07b7ac44b903/src/Http/Authenticator.php#L37

Т.к официального при у них нет.
