### ISSUE TITLE
Добавить выброс исключений при неудачной попытке авторизации 

### ISSUE THREAD

**Issue by rastafary74** [shoman4eg/moy-nalog#19]
Сейчас неудачная попытка получить токен по логину и паролю не приводит к ошибке выполнения скрипта, хотя по логике без токена дальнейшая работа невозможна.
Необходимо выбрасывать исключения, в идеале с той ошибкой которую возвращает сервер при неудачной авторизации.

**Comment by shoman4eg** [comment]
Implemented in #20
