### ISSUE TITLE
Ошибка Could not resolve host: lknpd.nalog.ru

### ISSUE THREAD

**Issue by AlexKomMsk** [shoman4eg/moy-nalog#21]
Сегодня стал получать ошибку в логах (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 6: Could not resolve host: lknpd.nalog.ru (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210)
Laravel 8, PHP7.4

**Comment by shoman4eg** [comment]
Можно попробовать сделать так
```
$httpClient = new GuzzleHttp\Client(['verify' => false]);
$apiClient = \Shoman4eg\Nalog\ApiClient::createWithCustomClient($httpClient);
```

**Comment by shoman4eg** [comment]
Хотя сейчас проверил, всё работает. Видимо сертификат починили.

**Comment by AlexKomMsk** [comment]
У меня продолжают падать ошибки. Сейчас она так выглядит cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to lknpd.nalog.ru:443 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://lknpd.nalog.ru/api/v1/auth/lkfl
