### ISSUE TITLE
Как авторизоваться по телефону или "ключам доступа"? 

### ISSUE THREAD

**Issue by nikita-komissarov** [shoman4eg/moy-nalog#22]
Упрощённый вариант регистрации через банк, предусматривает создание аккаунта по номеру телефона.
Например, у меня есть логин (ИНН), но нет пароля.

У тебя есть возможность добавить авторизацию с помощью внешних ключей (в том числе бессрочных), которые можно создать в разделе "Управление доступом", или по номеру телефона?

UPD
**Если у тебя тоже нет пароля** от ИНН на сайте "Мой налог", [здесь](https://github.com/shoman4eg/moy-nalog/issues/22#issuecomment-1324373046) информация как это сделать

**Comment by shoman4eg** [comment]
Не знаю как это происходит, но думаю, можно попробовать авторизоваться на странице https://lknpd.nalog.ru/auth/login, там есть авторизация по номеру телефона, и задать пароль.

**Comment by nikita-komissarov** [comment]
Я имею ввиду что в [описании метода авторизации](https://github.com/shoman4eg/moy-nalog#authorization), у тебя  пример только по логину (ИНН) и паролю. Но пароля может не быть, в случае регистрации через банк. Такие пользователи входят на сайт налоговой только по номеру телефона, так как не имеют пароля от своего ИНН.

Ты не планируешь добавить в метод авторизации возможность входа по телефону или [ключам доступа](https://lknpd.nalog.ru/settings/public-access)?

![image](https://user-images.githubusercontent.com/48474884/203380833-1cfa9bd7-7b63-460f-a694-fdbc85c23568.png)
![image](https://user-images.githubusercontent.com/48474884/203381055-d29221b9-a41e-48f8-a2b7-7e80ec9072ac.png)

**Comment by shoman4eg** [comment]
Я смысл понял. Дело в том, что я не могу это проверить и публичного апи у личного кабинета тоже нет.
Если сможешь дать дампы реквестов из инструметов разработчика в браузере при авторизации через телефон (убрав всю важную информацию, волнует только ) , то думаю что смогу добавить.

Судя по запросу `https://lknpd.nalog.ru/api/v2/auth/challenge/sms/start` при авторизации через телефон, там будет отправляться смс. Там важно получить `accessToken`  и способ не важен. 

А вот с ключами доступа не знаю как быть. Но если дашь больше информации, то в теории, смогу добавить.

**Comment by nikita-komissarov** [comment]
> Если сможешь дать дампы реквестов из инструметов разработчика в браузере при авторизации через телефон (убрав всю важную информацию, волнует только что надо передать и что приходит в ответе) , то думаю что смогу добавить.

## Вход на сайт "[Мой налог](https://lknpd.nalog.ru/auth/login)", с помощью номера телефона
Обрати внимание: в браузере, запрос на отправку SMS идёт на **v2**, а валидация на **v1**.
Но я не уверен, что вторая версия у них не может валидировать эти коды.

По поводу ключей доступа, постараюсь собрать информацию. Это было бы самым удобным и безопасным способом.
### Запрос с сообщением номера телефона:
``` 
curl 'https://lknpd.nalog.ru/api/v2/auth/challenge/sms/start' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Authorization;' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: _ym_uid=1666736533300201951; _ym_d=1666746533; _ym_isad=2; _ym_visorc=w' \
  -H 'Origin: https://lknpd.nalog.ru' \
  -H 'Referer: https://lknpd.nalog.ru/auth/login' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '{
    "phone":"79999999999",
    "requireTpToBeActive":true
  }' \
  --compressed
```

### В ответе получаем токен запроса и время его действия:

``` 
{
  "challengeToken":"CHALLENGE-TOKEN-36CHAR-****-************",
  "expireDate":"2022-11-22T23:04:53.818148Z",
  "expireIn":120
}
```

### Дожидаемся SMS с кодом подтверждения (6 символов) и отправляем запрос на верификацию кода вместе с токеном, из предыдущего запроса:

```
curl 'https://lknpd.nalog.ru/api/v1/auth/challenge/sms/verify' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Authorization;' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: _ym_uid=1666736533300201951; _ym_d=1666746533; _ym_isad=2; _ym_visorc=w' \
  -H 'Origin: https://lknpd.nalog.ru' \
  -H 'Referer: https://lknpd.nalog.ru/auth/login' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '{
    "phone":"79999999999",
    "code":"VERIFY-CODE-6CHAR",
    "challengeToken":"CHALLENGE-TOKEN-36CHAR-****-************",
    "deviceInfo":{
      "sourceDeviceId":"DEVICE-ID-21CHAR",
      "sourceType":"WEB",
      "appVersion":"1.0.0",
      "metaDetails":{
        "userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
      }
    }
  }' \
  --compressed
```

### Получаем ответ с токенами и информацией об аккаунте:

```
{
  "refreshToken":"REFRESH-TOKEN-432CHAR",
  "refreshTokenExpiresIn":null,
  "token":"ACCESS-TOKEN-364CHAR",
  "tokenExpireIn":"2022-11-23T00:03:11.084Z",
  "profile":{
    "lastName": null,
    "id": USER-ID-INT,
    "displayName": "DISPLAY-NAME",
    "middleName": null,
    "email": "USER-EMAIL",
    "phone": "79999999999",
    "inn": "USER-INN-12CHAR",
    "snils": "USER-SNILS-14CHAR",
    "avatarExists": false,
    "initialRegistrationDate": "2010-10-28T21:00:00Z",
    "registrationDate": "2010-10-29T10:26:00.344Z",
    "firstReceiptRegisterTime": "2020-03-13T17:56:21.175Z",
    "firstReceiptCancelTime": null,
    "hideCancelledReceipt": false,
    "registerAvailable": null,
    "status": "ACTIVE",
    "restrictedMode": false,
    "pfrUrl": null,
    "login": null
  }
}
```

**Comment by nikita-komissarov** [comment]
# Подсказка тем, у кого тоже нет пароля от "Мой налог", но есть доступ к порталу Госуслуг (ЕСИА)
В общем если зайти на [сайт налоговой](https://lkfl2.nalog.ru/), который не нужно путать с [сайтом для самозанятых](lknpd.nalog.ru), то там можно назначить почту, контрольный вопрос и задать/сменить пароль от аккаунта. Этот пароль подходит к обоим сервисам.

Авторизоваться на [сайте налоговой](https://lkfl2.nalog.ru/), как вы уже наверное поняли, можно с помощью портала госуслуг

**Comment by shoman4eg** [comment]
Информацию о получении пароля добавлю в ридми.
С авторизацией по телефону, в целом, можно добавить методы для получения токена. Но вся обработка, ввод смс уже будет на том, кто будет реализовывать авторизацию.

![image](https://user-images.githubusercontent.com/2788396/203545416-319f139f-4b11-4eea-ae30-3b986b7949ab.png)
Весь json ответ можно будет скопировать и использовать его для авторизации.

**Comment by nikita-komissarov** [comment]
> С авторизацией по телефону, в целом, можно добавить методы для получения токена. Но вся обработка, ввод смс уже будет на том, кто будет реализовывать авторизацию.

Реализовал методы запроса авторизации и подтверждения по телефону, добавил описание в ридми.
Прими [изменения](https://github.com/shoman4eg/moy-nalog/pull/23), если они подходят.

Не знаю, как это используют другие, но думаю можно сразу дополнить в коде пример временного хранения challenge-токена в куки.

По поводу "ключей доступа", мне так и не удалось найти информацию о том, как их правильно применять. Но я думаю что в ряде основных случаев, двух вариантов авторизации (учитывая что пароль и телефон — всё что доступно в интерфейсе самого сервиса) должно хватить.

**Comment by shoman4eg** [comment]
> Не знаю, как это используют другие, но думаю можно сразу дополнить в коде пример временного хранения challenge-токена в куки.

Думаю нет смысла писать про куки, т.к каждый может хранить где хочет. Кто-то в куках, кто-то в кеше и т.п.
Т.к всё равно надо хранить accessToken, чтобы не запрашивать его каждый раз.
