### ISSUE TITLE
Не получается использовать

### ISSUE THREAD

**Issue by Letomaniy** [shoman4eg/moy-nalog#27]
Пример кода:
```
<?php
date_default_timezone_set('Europe/Moscow');

require_once "../vendor/autoload.php";


 use Shoman4eg\Nalog\ApiClient;
	$apiClient = ApiClient::create();
?>
```

Проблема в том что скрипт ломается после вызова 
`$apiClient = ApiClient::create();`
переустанавливал composer несколько раз, думая что проблема в нём. Я впринципе не очень умею им пользоваться. Но судя по гайдам из интернета я всё сделал верно.

**Comment by nikita-komissarov** [comment]
Можешь прислать лог ошибки?

**Comment by Letomaniy** [comment]
> Можешь прислать лог ошибки?

А где я его могу найти?

**Comment by Letomaniy** [comment]
> Можешь прислать лог ошибки?

вот что выдаёт, ничего из этого мне не понятно)


`Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Symfony\Component\HttpClient\HttplugClient, Http\Adapter\Guzzle7\Client, Http\Adapter\Guzzle6\Client, Http\Adapter\Guzzle5\Client, Http\Client\Curl\Client, Http\Client\Socket\Client, Http\Adapter\Buzz\Client, Http\Adapter\React\Client, Http\Adapter\Cake\Client, Http\Adapter\Zend\Client, Http\Adapter\Artax\Client, Http\Discovery\Strategy\CommonClassesStrategy::buzzInstantiate. - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: . in /var/www/html/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41 Stack trace: #0 /var/www/html/vendor/php-http/discovery/src/ClassDis in /var/www/html/vendor/php-http/discovery/src/HttpClientDiscovery.php on line 27`

**Comment by nikita-komissarov** [comment]
> > Можешь прислать лог ошибки?
> 
> 
> 
> А где я его могу найти?
> 
> 

Вероятнее всего, твоя проблема связана не с библиотекой, а банально синтаксическая. Тебе нужно получать обратную связь от твоих скриптов после каждого выполнения, иначе работа и поиск ошибок будут крайне сложными. 

[https://yandex.ru/search?text=%D0%BA%D0%B0%D0%BA+%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C+%D0%BB%D0%BE%D0%B3+%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA+php](Яндекс поиск: "как посмотреть лог ошибок php")

**Comment by Letomaniy** [comment]
> > > Можешь прислать лог ошибки?
> > 
> > 
> > А где я его могу найти?
> 
> Вероятнее всего, твоя проблема связана не с библиотекой, а банально синтаксическая. Тебе нужно получать обратную связь от твоих скриптов после каждого выполнения, иначе работа и поиск ошибок будут крайне сложными.
> 
> [Яндекс поиск: "как посмотреть лог ошибок php"](https://yandex.ru/search?text=%D0%BA%D0%B0%D0%BA+%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C+%D0%BB%D0%BE%D0%B3+%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA+php)

Решил проблему. Прогуглил её _Most likely, your project is missing the message factories and/or a PRS-7 implementation._

и прописал это: `$ composer require php-http/curl-client guzzlehttp/psr7 php-http/message`

**Comment by Letomaniy** [comment]
> > > Можешь прислать лог ошибки?
> > 
> > 
> > А где я его могу найти?
> 
> Вероятнее всего, твоя проблема связана не с библиотекой, а банально синтаксическая. Тебе нужно получать обратную связь от твоих скриптов после каждого выполнения, иначе работа и поиск ошибок будут крайне сложными.
> 
> [Яндекс поиск: "как посмотреть лог ошибок php"](https://yandex.ru/search?text=%D0%BA%D0%B0%D0%BA+%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C+%D0%BB%D0%BE%D0%B3+%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA+php)

Спасибо вам что подтолкнули меня. Я бы не додумался включить лог ошибок в php, хотя это самое простое)

**Comment by shoman4eg** [comment]
@Letomaniy надо установить http-client.
К примеру еще написать `composer require guzzlehttp/guzzle`

**Comment by shoman4eg** [comment]
@nikita-komissarov возможно есть смысл ловить ошибку `DiscoveryFailedException` и выбрасывать своё исключение для того, чтобы пользователю было проще понять что надо установить пакет с `http-client`
