### ISSUE TITLE
php 8.2?

### ISSUE THREAD

**Issue by SmoKE585** [shoman4eg/moy-nalog#30]
Не могу установить, у меня стоит "brick/math": "^0.11.0" ругается на него :) и просит версию для php 7...

**Comment by SmoKE585** [comment]
Установил через форк, но все же.

**Comment by shoman4eg** [comment]
Так тут проблема с той версией которая уже установлена. 
В [`brick/math`](https://github.com/brick/math/blob/0.9.3/composer.json) версии 0.9.3 требования `"php": "^7.1 || ^8.0"`

Можно попробовать поставить >= 0.9 и создать пулл реквест
