### ISSUE TITLE
Падает ошибка в лог

### ISSUE THREAD

**Issue by AlexKomMsk** [shoman4eg/moy-nalog#33]
Добрый день. В логах с недавних пор ошибки.

`production.ERROR: Syntax error {"exception":"[object] (JsonException(code: 4): Syntax error at /vendor/shoman4eg/moy-nalog/src/Util/JSON.php:58`

Стек

```
#0 vendor/shoman4eg/moy-nalog/src/Util/JSON.php(58): json_decode()
#1 vendor/shoman4eg/moy-nalog/src/Http/AuthenticationPlugin.php(28): Shoman4eg\\Nalog\\Util\\JSON::decode()
#2 vendor/shoman4eg/moy-nalog/src/ApiClient.php(94): Shoman4eg\\Nalog\\Http\\AuthenticationPlugin->__construct()
Shoman4eg\\Nalog\\ApiClient->authenticate()
```

**Comment by shoman4eg** [comment]
А что передается в метод `$apiClient->authenticate($accessToken);`, `$accessToken` должен быть json строкой
