### ISSUE TITLE
Ошибка "Http\Client\Exception\NetworkException Idle timeout reached for "https://lknpd.nalog.ru/api/v1/income"."

### ISSUE THREAD

**Issue by M0EStRO** [shoman4eg/moy-nalog#34]
Систематически возникает ошибка "Http\Client\Exception\NetworkException Idle timeout reached for "https://lknpd.nalog.ru/api/v1/income"." После нее при попытке выставить чек получаю ошибку "Http\Client\Exception\NetworkException Could not resolve host: lknpd.nalog.ru for "https://lknpd.nalog.ru/api/v1/income"."

Laravel 8. PHP 8.1

Файл где возникает ошибка "/vendor/symfony/http-client/HttplugClient.php:106"

```php
public function sendRequest(RequestInterface $request): Psr7ResponseInterface
102     {
103         try {
104             return $this->waitLoop->createPsr7Response($this->sendPsr7Request($request));
105         } catch (TransportExceptionInterface $e) {
106             throw new NetworkException($e->getMessage(), $request, $e);
107         }
108     }
``` 

И так может продолжаться сутки-двое, потом снова работает.

И еще. В документации везде где указано
```php 
// UUID чека для операций запроса данных чека или его отмены
$receiptUuid = $createdincome->....
``` 
$createdincome нужно заменить на $createdIncome. 

Спасибо!

**Comment by shoman4eg** [comment]
`Could not resolve host`, это проблема не со стороны библиотеки.
https://github.com/guzzle/guzzle/issues/1996

**Comment by M0EStRO** [comment]
> `Could not resolve host`, это проблема не со стороны библиотеки. [guzzle/guzzle#1996](https://github.com/guzzle/guzzle/issues/1996)

Действительно, проблема была в блокировке IP хостера со стороны nalog.ru. Хостер решил проблему - все заработало. Спасибо за ответ и библиотеку
