### ISSUE TITLE
Не работает с Symfony 7

### ISSUE THREAD

**Issue by DmitrYs-1** [shoman4eg/moy-nalog#38]
При попытке подключения к symfony 7 получаю ошибку "No HTTPlug clients found. Make sure to install a package providing "php-http/client-implementation". Example: "php-http/guzzle6-adapter"."
symfony/http-client при этом установлен

**Comment by DmitrYs-1** [comment]
Временное решение в моём случае

src/Http/ClientConfigurator.php
![image](https://github.com/user-attachments/assets/b0572363-9725-4e2f-8df4-a12e60844679)

**Comment by shoman4eg** [comment]
Посмотрю, но чтобы не городить костыли с комментами, можно сделать 
```php
$apiClient = ApiClient::createWithCustomClient(new HttplugClient());
```

**Comment by shoman4eg** [comment]
Исправлено. Symfony обновили http client и не наследуются от http-client по которому проходила проверка. 
Поменял стратегию поиска, сейчас всё должнл быть ок

**Comment by DmitrYs-1** [comment]
Отлично, спасибо!
