### ISSUE TITLE
Указание источника/типа дохода

### ISSUE THREAD

**Issue by rastafary74** [shoman4eg/moy-nalog#5]
Поле 'incomeType' данных о клиенте 'client'
пример 
https://github.com/miglm/lknpd-nalog-api/blob/da7f5eb7c4d0e4456669bc4f26ec5c9f872e2ec6/LkNpdNalogApi.php#L121

1) FROM_INDIVIDUAL (доход от физического лица)
2) FROM_LEGAL_ENTITY (доход от юридического лица или ИП)
3) FROM_FOREIGN_AGENCY (доход от иностранной организации)

**Comment by shoman4eg** [comment]
Добавляется черещ IncomeClient
https://github.com/shoman4eg/moy-nalog#create-income-with-custom-client
