### ISSUE TITLE
Указание причины отмены чека

### ISSUE THREAD

**Issue by rastafary74** [shoman4eg/moy-nalog#6]
Поле "comment" запроса на урл /cancel
Пример
https://github.com/miglm/lknpd-nalog-api/blob/da7f5eb7c4d0e4456669bc4f26ec5c9f872e2ec6/LkNpdNalogApi.php#L140

По сути есть две причины:
'Чек сформирован ошибочно'
'Возврат средств'

**Comment by shoman4eg** [comment]
Эта возможность будет, её закладывал изначально

**Comment by shoman4eg** [comment]
Добавлено
Подробнее https://github.com/shoman4eg/moy-nalog#cancel-income
