### ISSUE TITLE
Указание название организации

### ISSUE THREAD

**Issue by rastafary74** [shoman4eg/moy-nalog#7]
Поле "displayName" данных клиента client
https://github.com/miglm/lknpd-nalog-api/blob/da7f5eb7c4d0e4456669bc4f26ec5c9f872e2ec6/LkNpdNalogApi.php#L119

**Comment by shoman4eg** [comment]
Это в процессе. Будет возможность задать

**Comment by shoman4eg** [comment]
Добавлено.
Задается через IncomeClient 
https://github.com/shoman4eg/moy-nalog#create-income-with-custom-client
